"""Kaggle workflow template used inside the generated self-contained runner."""

from __future__ import annotations

import hashlib
import importlib.metadata
import json
import shutil
import subprocess
import sys
import threading
import time
import traceback
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import replace
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def render_runner(archive_b64: str, archive_sha256: str, archive_bytes: int) -> str:
    """Render a self-contained Kaggle Python script with an embedded source archive."""
    return f'''# Generated by scripts/build_kaggle_runner.py. Do not edit directly.
from __future__ import annotations

import base64
import io
import json
import sys
import tarfile
from pathlib import Path

PROJECT_ARCHIVE_B64 = "{archive_b64}"
PROJECT_ARCHIVE_SHA256 = "{archive_sha256}"
PROJECT_ARCHIVE_BYTES = {archive_bytes}


def _install_project() -> Path:
    import hashlib

    project = Path("/kaggle/working/project")
    project.mkdir(parents=True, exist_ok=True)
    payload = base64.b64decode(PROJECT_ARCHIVE_B64, validate=True)
    if len(payload) != PROJECT_ARCHIVE_BYTES:
        raise RuntimeError("embedded project archive byte count mismatch")
    if hashlib.sha256(payload).hexdigest() != PROJECT_ARCHIVE_SHA256:
        raise RuntimeError("embedded project archive SHA-256 mismatch")
    with tarfile.open(fileobj=io.BytesIO(payload), mode="r:gz") as archive:
        members = archive.getmembers()
        for member in members:
            name = Path(member.name)
            if name.is_absolute() or ".." in name.parts or member.issym() or member.islnk():
                raise RuntimeError(f"unsafe embedded archive member: {{member.name}}")
        for member in members:
            archive.extract(member, project)
    return project


def main() -> None:
    project = _install_project()
    sys.path.insert(0, str(project))
    sys.path.insert(0, str(project / "src"))
    from scripts.kaggle_runner import run_kaggle_workflow

    run_kaggle_workflow(project, PROJECT_ARCHIVE_SHA256, PROJECT_ARCHIVE_BYTES)


if __name__ == "__main__":
    main()
'''


@contextmanager
def heartbeat(phase: str, *, interval_seconds: int = 60) -> Iterator[None]:
    stop = threading.Event()
    started = time.perf_counter()

    def report() -> None:
        while not stop.wait(interval_seconds):
            emit(phase, "running", elapsed_seconds=round(time.perf_counter() - started, 3))

    thread = threading.Thread(target=report, daemon=True)
    thread.start()
    try:
        yield
    finally:
        stop.set()
        thread.join()


def emit(phase: str, status: str, **details: object) -> None:
    print(json.dumps({"phase": phase, "status": status, **details}, sort_keys=True, default=str), flush=True)


def run_kaggle_workflow(project: Path, archive_sha256: str, archive_bytes: int) -> None:
    """Run the release pipeline and persist failure metadata before re-raising."""
    artifacts = Path("/kaggle/working/artifacts")
    started = time.perf_counter()
    phase = "install_project"
    try:
        _ensure_runtime_dependencies()
        phase = "gpu_preflight"
        report = _gpu_preflight()
        emit(phase, "completed", **report)

        from instance_segmenter.config import load_config
        from instance_segmenter.data.manifest import read_manifest, verify_prepared_data
        from instance_segmenter.evaluation.evaluate import evaluate_checkpoint
        from instance_segmenter.inference.predictor import Predictor
        from instance_segmenter.training.train import run_training
        from scripts.download_data import download_penn_fudan
        from scripts.preview_dataset import render_preview

        data_dir = Path("/kaggle/working/data")
        manifest_dir = Path("/kaggle/working/manifests")
        _copy_fixed_manifests(project / "data" / "manifests", manifest_dir)

        phase = "download_pennfudan"
        emit(phase, "started")
        with heartbeat(phase):
            download_penn_fudan(data_dir, manifest_dir)
        emit(phase, "completed")

        phase = "prepare_data"
        emit(phase, "started")
        with heartbeat(phase):
            metadata = verify_prepared_data(data_dir, manifest_dir)
        expected_counts = {"train": 136, "valid": 17, "test": 17}
        expected_identity = "64bfbd3df4c33b089e2c8710795f43bd21c856ff7001747447ab9849af7b48d8"
        if metadata.split_counts != expected_counts:
            raise RuntimeError("unexpected Penn-Fudan split counts: " + str(metadata.split_counts))
        if metadata.identity != expected_identity or metadata.split_strategy != "source-stratified-sha256-v2":
            raise RuntimeError("unexpected Penn-Fudan protocol-v2 dataset identity")
        emit(phase, "completed", dataset_identity=metadata.identity, split_counts=metadata.split_counts)

        phase = "inspect_data"
        emit(phase, "started")
        preview = artifacts / "dataset-preview.png"
        render_preview(data_dir, manifest_dir, preview, limit=4)
        emit(phase, "completed", preview=str(preview))

        base = load_config(project / "configs" / "reference_maskrcnn.yaml")
        config = replace(
            base,
            run=replace(base.run, output_dir=artifacts),
            data=replace(base.data, root=data_dir, manifest_dir=manifest_dir, num_workers=2),
            training=replace(base.training, amp=True),
            device="cuda",
        )

        phase = "dry_run"
        emit(phase, "started")
        with heartbeat(phase):
            diagnostic = run_training(config, dry_run_mode=True)
        if diagnostic.dry_run_result is None:
            raise RuntimeError("dry-run did not produce diagnostics")
        _clear_cuda_cache()
        emit(phase, "completed", losses=diagnostic.dry_run_result.losses)

        phase = "training"
        emit(phase, "started", epochs=config.training.epochs)
        training_started = time.perf_counter()
        with heartbeat(phase):
            result = run_training(config)
        training_seconds = time.perf_counter() - training_started
        if result.completed_epochs != 20:
            raise RuntimeError("reference run completed " + str(result.completed_epochs) + " epochs, expected 20")
        emit(phase, "completed", completed_epochs=result.completed_epochs, best_epoch=result.best_epoch)

        phase = "evaluation"
        emit(phase, "started")
        evaluation_started = time.perf_counter()
        with heartbeat(phase):
            evaluation = evaluate_checkpoint(
                result.run_dir / "best.pt",
                split="test",
                output_dir=result.run_dir / "evaluation",
                device="cuda",
                plot=True,
            )
        evaluation_seconds = time.perf_counter() - evaluation_started
        emit(phase, "completed", metrics=evaluation.metrics, image_count=evaluation.image_count)

        phase = "prediction"
        emit(phase, "started")
        prediction_started = time.perf_counter()
        test_row = read_manifest(manifest_dir / "test.csv")[0]
        prediction = Predictor.from_checkpoint(result.run_dir / "best.pt", device="cuda").predict_single(
            data_dir / metadata.dataset_root / test_row.image_path,
            result.run_dir / "predictions" / test_row.image_id,
        )
        prediction_seconds = time.perf_counter() - prediction_started
        emit(phase, "completed", instance_count=prediction.instance_count, output=str(prediction.output_dir))

        phase = "cleanup"
        emit(phase, "started")
        _cleanup_runtime_outputs(project, data_dir, manifest_dir)
        emit(phase, "completed")

        phase = "finalize"
        summary = _write_success_summary(
            artifacts=artifacts,
            result=result,
            evaluation=evaluation,
            metadata=metadata,
            report=report,
            archive_sha256=archive_sha256,
            archive_bytes=archive_bytes,
            training_seconds=training_seconds,
            evaluation_seconds=evaluation_seconds,
            prediction_seconds=prediction_seconds,
            total_seconds=time.perf_counter() - started,
        )
        emit(phase, "completed", summary=summary)
    except Exception as exc:
        artifacts.mkdir(parents=True, exist_ok=True)
        failure = {
            "status": "error",
            "phase": phase,
            "exception_type": type(exc).__name__,
            "message": str(exc),
            "traceback": traceback.format_exc(),
            "elapsed_seconds": round(time.perf_counter() - started, 3),
        }
        (artifacts / "kaggle-run-failure.json").write_text(json.dumps(failure, indent=2) + "\n", encoding="utf-8")
        emit(phase, "failed", exception_type=type(exc).__name__, message=str(exc))
        raise


def _ensure_runtime_dependencies() -> None:
    missing: list[str] = []
    for module, requirement in (("torchmetrics", "torchmetrics>=1.4,<2"), ("pycocotools", "pycocotools>=2.0.7,<3")):
        try:
            __import__(module)
        except ModuleNotFoundError:
            missing.append(requirement)
    if missing:
        subprocess.run([sys.executable, "-m", "pip", "install", *missing], check=True)


def _gpu_preflight() -> dict[str, object]:
    import torch
    import torchvision

    if not torch.cuda.is_available():
        raise RuntimeError("Kaggle kernel started without CUDA; request a T4 or newer GPU")
    capability = torch.cuda.get_device_capability(0)
    if capability[0] < 7:
        raise RuntimeError(
            "allocated GPU sm_"
            + str(capability[0])
            + str(capability[1])
            + " is unsupported by current PyTorch; request a T4 or newer GPU"
        )
    return {
        "device": "cuda:0",
        "gpu_name": torch.cuda.get_device_name(0),
        "cuda_device_count": torch.cuda.device_count(),
        "compute_capability": capability,
        "cuda_version": torch.version.cuda,
        "torch_version": torch.__version__,
        "torchvision_version": torchvision.__version__,
    }


def _copy_fixed_manifests(source: Path, destination: Path) -> None:
    required = ("train.csv", "valid.csv", "test.csv", "dataset.yaml")
    if not all((source / name).is_file() for name in required):
        raise RuntimeError("embedded project lacks fixed manifests in " + str(source))
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source, destination)


def _cleanup_runtime_outputs(project: Path, data_dir: Path, manifest_dir: Path) -> None:
    """Keep downloaded Kaggle outputs focused on artifacts rather than runtime inputs."""
    for path in (project, data_dir, manifest_dir):
        if path.exists():
            shutil.rmtree(path)


def _clear_cuda_cache() -> None:
    import gc

    import torch

    gc.collect()
    torch.cuda.empty_cache()


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _write_success_summary(
    *,
    artifacts: Path,
    result: Any,
    evaluation: Any,
    metadata: Any,
    report: dict[str, object],
    archive_sha256: str,
    archive_bytes: int,
    training_seconds: float,
    evaluation_seconds: float,
    prediction_seconds: float,
    total_seconds: float,
) -> str:
    import torch
    import torchmetrics
    import torchvision

    run_dir = result.run_dir
    summary = {
        "status": "complete",
        "completed_at_utc": datetime.now(timezone.utc).isoformat(),
        "python_version": sys.version,
        "torch_version": torch.__version__,
        "torchvision_version": torchvision.__version__,
        "torchmetrics_version": torchmetrics.__version__,
        "pycocotools_version": importlib.metadata.version("pycocotools"),
        "gpu": report,
        "source_archive_sha256": archive_sha256,
        "source_archive_bytes": archive_bytes,
        "resolved_config_sha256": _sha256(run_dir / "config.yaml"),
        "dataset_identity": metadata.identity,
        "manifest_format_version": metadata.manifest_format_version,
        "split_strategy": metadata.split_strategy,
        "split_seed": metadata.split_seed,
        "split_counts": metadata.split_counts,
        "split_hashes": metadata.split_hashes,
        "completed_epochs": result.completed_epochs,
        "best_epoch": result.best_epoch,
        "best_valid_mask_map": result.best_metric,
        "metric_protocol": "COCO confidence ranking; no display-threshold filtering",
        "metric_score_floor": 0.0,
        "training_seconds": round(training_seconds, 3),
        "evaluation_seconds": round(evaluation_seconds, 3),
        "prediction_seconds": round(prediction_seconds, 3),
        "total_seconds": round(total_seconds, 3),
        "metrics": evaluation.metrics,
        "image_count": evaluation.image_count,
        "target_count": evaluation.target_count,
        "prediction_count": evaluation.prediction_count,
        "checkpoint_sha256": _sha256(run_dir / "best.pt"),
        "last_checkpoint_sha256": _sha256(run_dir / "last.pt"),
        "checkpoint": str(run_dir / "best.pt"),
        "evaluation_dir": str(evaluation.output_dir),
    }
    output = artifacts / "kaggle-run-summary.json"
    output.write_text(json.dumps(summary, indent=2, sort_keys=True, default=str) + "\n", encoding="utf-8")
    return str(output)
